### ISSUE TITLE
Project quotas are not set after running this module

### ISSUE THREAD

**Issue by ljmc-github** [bushvin/ansible-module-xfs_quota#4]
Hi,

I just used this module to set up project quotas on XFS directories as per the task I join, but then when connecting to the target machine, the projects do not seem to be set.

I dd'ed a 1GB file in there and chowned it to the expected owner but it is not accounted for the project in xfs_quota report.

`/etc/projects` and `/etc/projid` are set correctly.

From the correct path, `xfs_quota> project -c home_bvance` gives:
```
Checking project home_bvance (path /stor/home/bvance)...
/stor/home/bvance - project identifier is not set (inode=0, tree=12)
/stor/home/bvance - project inheritance flag is not set
Processed 1 (/etc/projects and cmdline) paths for project home_bvance with recursion depth infinite (-1).
```

So, I force set the project with `xfs_quota> project -s home_bvance` which gives:
```
Setting up project home_bvance (path /stor/home/bvance)...
Processed 1 (/etc/projects and cmdline) paths for project home_bvance with recursion depth infinite (-1).
```

Then, `xfs_quota> project -c home_bvance` gives:
```
Checking project home_bvance (path /stor/home/bvance)...
Processed 1 (/etc/projects and cmdline) paths for project home_bvance with recursion depth infinite (-1).
```

And the 1GB file is reported correctly in the report.

Thanks for the module, I hope there is a solution for this.

Task:
```
    - name: Set default soft and hard limits for homedirs
      xfs_quota:
        type: project
        name: "home_{{ item.name }}"
        mountpoint: "/stor"
        bsoft: 40G
        bhard: 50G
        state: present
      loop: "{{ users }}"
      register: pquota_out
```

Output results:
```
{
  "ansible_loop_var": "item",
  "bhard": 53687091200,
  "bsoft": 42949672960,
  "changed": true,
  "failed": false,
  "invocation": {
    "module_args": {
      "bhard": "50G",
      "bsoft": "40G",
      "ihard": null,
      "isoft": null,
      "mountpoint": "/stor",
      "name": "home_bvance",
      "rtbhard": null,
      "rtbsoft": null,
      "state": "present",
      "type": "project"
    }
  },
  "item": {
    "email": "bob@vance-refrigeration.com",
    "fn": "Bob",
    "ln": "Vance",
    "name": "bvance"
  },
  "xfs_quota": {
    "bhard": null,
    "bsoft": null,
    "ihard": null,
    "isoft": null,
    "rtbhard": null,
    "rtbsoft": null
  }
}
```

EDIT: correct a typo

**Comment by bushvin** [comment]
I will try to find some time to troubleshoot this.

**Comment by bushvin** [comment]
I didn't realise where this issue was made. I actually got the module into the ansible project as one of the modules since v2.8
I did some additional refactoring and bugfixes to get it in, so could you check if you experience the same issue with the same module in Ansible 2.8 ?
Thanks

**Comment by ljmc-github** [comment]
My bad, I didn't know where to log the issue so I created it in the module. Do you want me to move it ?

Also, I am using ansible 2.9.11 provided in RHEL 8. Anything you need me to test in this setup ?

**Comment by bushvin** [comment]
That's fine. I just wanted to make sure you were using the one included with Ansible.
Maybe in the future, open an issue on the ansible project, but I'll trace the issue here...

Will try to free up some time this week to test/troubleshoot this.
I think I have everything, but if you could provide me with the relevant bits from '/etc/projid' and '/etc/projects' that would be awesome!

**Comment by ljmc-github** [comment]
`/etc/projects`
```
# user homedirs 10:99 in /stor/home
10:/stor/home/bvance
```
`/etc/projid`
```
# user homedirs 10:99 as home_user:number
home_bvance:10
```

**Comment by ljmc-github** [comment]
Just a quick ping to check if there is any solution to this, especially since 2.10 came out recently. :)

**Comment by bushvin** [comment]
Apologies, life happened.
I'll make sure to make modifications for both 2.9 and 2.10

**Comment by ljmc-github** [comment]
No worries, I was just checking. It's fairly easy to just issue the xfs_quota set command.

**Comment by bushvin** [comment]
yes, I pinpointed it down to a change in output on xfs_quota's part...


Before doeing anything, I perform the following:

````xfs_quota> project <project name>````
And back in the days when I wrote this, the result for a  non-initialized project directory was
````Project Id '<project name>' - is not set.````
Now it seems to have changed to
````project identifier is not set````

In a way, this is good, as looking for it becomes easier...
I'll post an update here shortly

**Comment by bushvin** [comment]
@BiochemLouis I've updated this repo for testing purposes.
When you have time, could you test? If it works as well on your end, I will do the necessary to update the relevant ansible repo's

**Comment by ljmc-github** [comment]
Servers are down for the afternoon and maybe tomorrow, I'll spin up a VM as soon as possible.

**Comment by ljmc-github** [comment]
Works perfectly, tested with the following playbook in a Centos 8 server VM.

```
---

- hosts: localhost
  become: true

  tasks:
    - name: test quotas
      xfs_quota:
        type: project
        name: "home_{{item}}"
        mountpoint: /mnt/quotadisk
        bsoft: 1G
        bhard: 1.5G
        isoft: 100
        ihard: 150
        state: present
      loop:
        - alice
        - bob
```
